server:
  port: 8080

spring:
  application:
    name: servicio-pedidos

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:h2:mem:pedidosdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

resilience4j:
  circuitbreaker:
    instances:
      inventarioService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true